# Generated by Django 4.2 on 2023-04-19 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rewards",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Wallet_id", models.CharField(max_length=200, unique=True)),
                (
                    "wallet_total",
                    models.FloatField(blank=True, max_length=10, null=True),
                ),
                ("transaction_log", models.JSONField(blank=True, null=True)),
                ("is_volunteer", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Volunteer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pan_no", models.CharField(max_length=14, unique=True)),
                ("country", models.CharField(max_length=50)),
                ("state", models.TextField(max_length=50)),
                ("city", models.TextField(max_length=50)),
                (
                    "apartment_add",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
